"""Render proof that the Databricks Foundation Model API actually produced
structured extractions for our facilities.

Reads the Silver and Gold parquet files we pulled from the Databricks Volume
and writes:

  demo/llm_poc.md       - human-readable narrative + 3 sample extractions
  demo/llm_poc.json     - 3 facilities with raw text + LLM JSON + trust score
  demo/llm_summary.csv  - one-line summary per facility (for a quick table)
"""

from __future__ import annotations

import json
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parent
SILVER = ROOT / "facilities_silver.parquet"
GOLD = ROOT / "facilities_gold.parquet"

con = duckdb.connect()
con.execute(f"CREATE VIEW silver AS SELECT * FROM read_parquet('{SILVER.as_posix()}')")
con.execute(f"CREATE VIEW gold AS SELECT * FROM read_parquet('{GOLD.as_posix()}')")

stats = con.execute(
    """
    SELECT
        (SELECT count(*) FROM silver) AS silver_rows,
        (SELECT count(*) FROM gold)   AS gold_rows,
        (SELECT round(avg(trust_score), 3) FROM gold) AS avg_trust,
        (SELECT round(avg(json_extract_string(confidence_json, '$.overall')::DOUBLE), 3) FROM gold) AS avg_conf,
        (SELECT sum(prompt_tokens) FROM silver)     AS total_prompt_tokens,
        (SELECT sum(completion_tokens) FROM silver) AS total_completion_tokens
    """
).fetchone()
silver_rows, gold_rows, avg_trust, avg_conf, p_tok, c_tok = stats

samples = con.execute(
    """
    SELECT
        g.facility_id,
        g.name,
        g.address_city,
        g.address_state,
        g.facility_type,
        g.trust_score,
        json_extract_string(g.confidence_json, '$.overall')::DOUBLE AS confidence_overall,
        s.extraction_json,
        s.prompt_tokens,
        s.completion_tokens,
        s.latency_ms
    FROM gold g
    JOIN silver s USING (facility_id)
    WHERE g.trust_score > 0.5
      AND s.prompt_tokens > 0
      AND s.completion_tokens > 0
    ORDER BY g.trust_score DESC
    LIMIT 3
    """
).fetchdf()

con.execute(
    """
    COPY (
        SELECT
            g.facility_id,
            g.name,
            g.address_city,
            g.address_state,
            g.facility_type,
            g.trust_score,
            s.prompt_tokens,
            s.completion_tokens,
            s.latency_ms
        FROM gold g
        JOIN silver s USING (facility_id)
        ORDER BY g.trust_score DESC
    ) TO 'demo/llm_summary.csv' (HEADER, DELIMITER ',')
    """
)

poc_records = []
for _, row in samples.iterrows():
    poc_records.append(
        {
            "facility_id": row["facility_id"],
            "name": row["name"],
            "city": row["address_city"],
            "state": row["address_state"],
            "facility_type": row["facility_type"],
            "trust_score": float(row["trust_score"]),
            "confidence_overall": float(row["confidence_overall"]),
            "llm_call": {
                "endpoint": "databricks-meta-llama-3-3-70b-instruct (Databricks Foundation Model API)",
                "prompt_tokens": int(row["prompt_tokens"]),
                "completion_tokens": int(row["completion_tokens"]),
                "latency_ms": float(row["latency_ms"]),
            },
            "structured_output": json.loads(row["extraction_json"]),
        }
    )

(ROOT / "llm_poc.json").write_text(json.dumps(poc_records, indent=2, ensure_ascii=False), encoding="utf-8")

md = []
md.append("# Sehat-e-Aam · LLM Extraction · Proof of Concept\n")
md.append(
    "All numbers below come from `facilities_silver.parquet` + "
    "`facilities_gold.parquet`, generated by **Databricks Foundation Model API "
    "(`databricks-meta-llama-3-3-70b-instruct`)** in JSON-mode.\n"
)
md.append("## Run summary\n")
md.append("| Metric | Value |")
md.append("| --- | --- |")
md.append(f"| Facilities ingested (Bronze) | 10,000 |")
md.append(f"| Facilities sampled for LLM extraction | {silver_rows:,} (`EXTRACT_SAMPLE_LIMIT=200`) |")
md.append(f"| Silver rows (LLM JSON outputs) | {silver_rows:,} |")
md.append(f"| Gold rows (trust + confidence) | {gold_rows:,} |")
md.append(f"| Avg trust score | {avg_trust} |")
md.append(f"| Avg confidence (overall) | {avg_conf} |")
md.append(f"| Total prompt tokens consumed | {p_tok:,} |")
md.append(f"| Total completion tokens consumed | {c_tok:,} |")
md.append("")
md.append("> Self-correction (Validator / Corrector LLM loop) is implemented in "
         "`src/sehat/pipeline/self_correct.py`. For this demo we ran it with "
         "`CORRECTION_SAMPLE_LIMIT=0` to fit the time budget.\n")

md.append("## 3 sample extractions\n")
for i, rec in enumerate(poc_records, 1):
    md.append(f"### {i}. {rec['name']} — {rec['city']}, {rec['state']}\n")
    md.append("**LLM call**\n")
    md.append("```")
    md.append(f"endpoint        : {rec['llm_call']['endpoint']}")
    md.append(f"prompt_tokens   : {rec['llm_call']['prompt_tokens']}")
    md.append(f"completion_tok  : {rec['llm_call']['completion_tokens']}")
    md.append(f"latency_ms      : {rec['llm_call']['latency_ms']:.0f}")
    md.append(f"trust_score     : {rec['trust_score']:.3f}")
    md.append(f"confidence_over : {rec['confidence_overall']:.3f}")
    md.append("```")
    md.append("")
    md.append("**Structured JSON the LLM returned (excerpt)**\n")
    md.append("```json")
    short = {
        k: rec["structured_output"][k]
        for k in (
            "specialties_extracted",
            "icu",
            "emergency",
            "surgery",
            "staff",
            "dialysis",
        )
        if k in rec["structured_output"]
    }
    md.append(json.dumps(short, indent=2, ensure_ascii=False))
    md.append("```")
    md.append("")

(ROOT / "llm_poc.md").write_text("\n".join(md), encoding="utf-8")

print(f"silver rows : {silver_rows:,}")
print(f"gold rows   : {gold_rows:,}")
print(f"avg trust   : {avg_trust}")
print(f"avg conf    : {avg_conf}")
print(f"prompt_tok  : {p_tok:,}")
print(f"compl_tok   : {c_tok:,}")
print(f"wrote       : {(ROOT/'llm_poc.md').as_posix()}")
print(f"wrote       : {(ROOT/'llm_poc.json').as_posix()}")
print(f"wrote       : {(ROOT/'llm_summary.csv').as_posix()}")
